version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mercado_bitcoin_app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/mercadobitcoin_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=962e1cda9a517b53fe1996906f5632cc58e78d35fbabf9dd5433048bf00fa307
      - JWT_EXPIRE_MINUTES=60
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: mercado_bitcoin_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mercadobitcoin_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: mercado_bitcoin_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
